structures = [
    {"blocks": [{"width": 2, "height": 4, "x": 0, "y": 0}, {"width": 2, "height": 1, "x": 2, "y": 0}, {"width": 2, "height": 2, "x": 4, "y": 0}, {"width": 2, "height": 2, "x": 6, "y": 0}, {"width": 1, "height": 2, "x": 3, "y": 1}, {"width": 1, "height": 2, "x": 4, "y": 2}, {"width": 1, "height": 2, "x": 7, "y": 2}, {"width": 2, "height": 1, "x": 0, "y": 4}, {"width": 1, "height": 2, "x": 4, "y": 4}, {"width": 1, "height": 2, "x": 7, "y": 4}, {"width": 2, "height": 1, "x": 0, "y": 5}, {"width": 2, "height": 1, "x": 0, "y": 6}, {"width": 4, "height": 2, "x": 4, "y": 6}, {"width": 2, "height": 1, "x": 0, "y": 7}]},
    {"blocks": [{"width": 4, "height": 2, "x": 0, "y": 0}, {"width": 2, "height": 1, "x": 4, "y": 0}, {"width": 2, "height": 4, "x": 6, "y": 0}, {"width": 2, "height": 2, "x": 4, "y": 1}, {"width": 2, "height": 4, "x": 1, "y": 2}, {"width": 2, "height": 2, "x": 4, "y": 3}, {"width": 2, "height": 2, "x": 6, "y": 4}, {"width": 2, "height": 1, "x": 4, "y": 5}, {"width": 1, "height": 2, "x": 1, "y": 6}, {"width": 4, "height": 2, "x": 2, "y": 6}, {"width": 2, "height": 2, "x": 6, "y": 6}]},
    {"blocks": [{"width": 4, "height": 2, "x": 0, "y": 0}, {"width": 2, "height": 4, "x": 4, "y": 0}, {"width": 1, "height": 2, "x": 7, "y": 0}, {"width": 2, "height": 4, "x": 0, "y": 2}, {"width": 2, "height": 4, "x": 2, "y": 2}, {"width": 1, "height": 2, "x": 7, "y": 2}, {"width": 1, "height": 2, "x": 5, "y": 4}, {"width": 1, "height": 2, "x": 7, "y": 4}, {"width": 1, "height": 2, "x": 1, "y": 6}, {"width": 2, "height": 1, "x": 2, "y": 6}, {"width": 4, "height": 2, "x": 4, "y": 6}, {"width": 2, "height": 1, "x": 2, "y": 7}]},
    {"blocks": [{"width": 2, "height": 1, "x": 0, "y": 0}, {"width": 2, "height": 1, "x": 2, "y": 0}, {"width": 2, "height": 1, "x": 5, "y": 0}, {"width": 2, "height": 2, "x": 0, "y": 1}, {"width": 2, "height": 4, "x": 2, "y": 1}, {"width": 2, "height": 1, "x": 5, "y": 1}, {"width": 4, "height": 2, "x": 4, "y": 2}, {"width": 4, "height": 2, "x": 4, "y": 4}, {"width": 1, "height": 2, "x": 1, "y": 3}, {"width": 2, "height": 2, "x": 2, "y": 5}, {"width": 2, "height": 1, "x": 4, "y": 6}, {"width": 2, "height": 1, "x": 6, "y": 6}, {"width": 2, "height": 1, "x": 2, "y": 7}, {"width": 2, "height": 1, "x": 4, "y": 7}, {"width": 2, "height": 1, "x": 6, "y": 7}]},
    {"blocks": [{"width": 2, "height": 4, "x": 0, "y": 0}, {"width": 2, "height": 2, "x": 3, "y": 0}, {"width": 2, "height": 2, "x": 5, "y": 0}, {"width": 2, "height": 4, "x": 2, "y": 2}, {"width": 2, "height": 2, "x": 5, "y": 2}, {"width": 4, "height": 2, "x": 4, "y": 4}, {"width": 1, "height": 2, "x": 2, "y": 6}, {"width": 1, "height": 2, "x": 3, "y": 6}, {"width": 2, "height": 1, "x": 4, "y": 6}, {"width": 1, "height": 2, "x": 6, "y": 6}, {"width": 1, "height": 2, "x": 7, "y": 6}, {"width": 2, "height": 1, "x": 4, "y": 7}]},
    {"blocks": [{"width": 2, "height": 1, "x": 1, "y": 0}, {"width": 4, "height": 2, "x": 4, "y": 0}, {"width": 4, "height": 2, "x": 0, "y": 1}, {"width": 2, "height": 1, "x": 6, "y": 2}, {"width": 2, "height": 1, "x": 0, "y": 3}, {"width": 4, "height": 2, "x": 3, "y": 3}, {"width": 1, "height": 2, "x": 7, "y": 3}, {"width": 2, "height": 1, "x": 0, "y": 4}, {"width": 2, "height": 2, "x": 0, "y": 5}, {"width": 2, "height": 1, "x": 2, "y": 5}, {"width": 2, "height": 1, "x": 5, "y": 5}, {"width": 1, "height": 2, "x": 2, "y": 6}, {"width": 1, "height": 2, "x": 3, "y": 6}, {"width": 2, "height": 2, "x": 5, "y": 6}, {"width": 2, "height": 1, "x": 0, "y": 7}]},
    {"blocks": [{"width": 4, "height": 2, "x": 0, "y": 0}, {"width": 2, "height": 2, "x": 5, "y": 0}, {"width": 2, "height": 1, "x": 0, "y": 2}, {"width": 1, "height": 2, "x": 2, "y": 2}, {"width": 4, "height": 2, "x": 4, "y": 2}, {"width": 1, "height": 2, "x": 0, "y": 3}, {"width": 1, "height": 2, "x": 1, "y": 3}, {"width": 1, "height": 2, "x": 2, "y": 4}, {"width": 1, "height": 2, "x": 5, "y": 4}, {"width": 2, "height": 1, "x": 6, "y": 4}, {"width": 1, "height": 2, "x": 1, "y": 5}, {"width": 1, "height": 2, "x": 6, "y": 5}, {"width": 1, "height": 2, "x": 7, "y": 5}, {"width": 1, "height": 2, "x": 2, "y": 6}, {"width": 1, "height": 2, "x": 5, "y": 6}, {"width": 2, "height": 1, "x": 6, "y": 7}]},
    {"blocks": [{"width": 2, "height": 4, "x": 1, "y": 0}, {"width": 4, "height": 2, "x": 3, "y": 0}, {"width": 4, "height": 2, "x": 4, "y": 2}, {"width": 4, "height": 2, "x": 0, "y": 4}, {"width": 2, "height": 2, "x": 4, "y": 4}, {"width": 1, "height": 2, "x": 7, "y": 4}, {"width": 2, "height": 1, "x": 1, "y": 6}, {"width": 4, "height": 2, "x": 3, "y": 6}, {"width": 1, "height": 2, "x": 7, "y": 6}]},
    {"blocks": [{"width": 2, "height": 1, "x": 0, "y": 0}, {"width": 4, "height": 2, "x": 2, "y": 0}, {"width": 2, "height": 4, "x": 6, "y": 0}, {"width": 2, "height": 2, "x": 0, "y": 1}, {"width": 2, "height": 2, "x": 3, "y": 2}, {"width": 2, "height": 1, "x": 0, "y": 3}, {"width": 2, "height": 1, "x": 0, "y": 4}, {"width": 4, "height": 2, "x": 2, "y": 4}, {"width": 1, "height": 2, "x": 7, "y": 4}, {"width": 1, "height": 2, "x": 1, "y": 5}, {"width": 2, "height": 2, "x": 3, "y": 6}, {"width": 1, "height": 2, "x": 5, "y": 6}]},
    {"blocks": [{"width": 4, "height": 2, "x": 0, "y": 0}, {"width": 4, "height": 2, "x": 4, "y": 0}, {"width": 1, "height": 2, "x": 1, "y": 2}, {"width": 2, "height": 2, "x": 3, "y": 2}, {"width": 1, "height": 2, "x": 7, "y": 2}, {"width": 4, "height": 2, "x": 0, "y": 4}, {"width": 4, "height": 2, "x": 4, "y": 4}, {"width": 2, "height": 1, "x": 5, "y": 6}, {"width": 1, "height": 2, "x": 7, "y": 6}, {"width": 2, "height": 1, "x": 5, "y": 7}]},
    {"blocks": [{"width": 2, "height": 1, "x": 1, "y": 0}, {"width": 4, "height": 2, "x": 3, "y": 0}, {"width": 2, "height": 1, "x": 1, "y": 1}, {"width": 4, "height": 2, "x": 0, "y": 2}, {"width": 4, "height": 2, "x": 4, "y": 2}, {"width": 2, "height": 1, "x": 0, "y": 4}, {"width": 4, "height": 2, "x": 3, "y": 4}, {"width": 1, "height": 2, "x": 1, "y": 5}, {"width": 2, "height": 2, "x": 2, "y": 6}, {"width": 4, "height": 2, "x": 4, "y": 6}]},
    {"blocks": [{"width": 4, "height": 2, "x": 1, "y": 0}, {"width": 1, "height": 2, "x": 7, "y": 0}, {"width": 4, "height": 2, "x": 0, "y": 2}, {"width": 1, "height": 2, "x": 4, "y": 2}, {"width": 1, "height": 2, "x": 7, "y": 2}, {"width": 4, "height": 2, "x": 4, "y": 4}, {"width": 2, "height": 1, "x": 4, "y": 6}, {"width": 2, "height": 1, "x": 6, "y": 6}, {"width": 2, "height": 1, "x": 4, "y": 7}, {"width": 2, "height": 1, "x": 6, "y": 7}]},
    {"blocks": [{"width": 1, "height": 2, "x": 0, "y": 0}, {"width": 4, "height": 2, "x": 3, "y": 0}, {"width": 1, "height": 2, "x": 0, "y": 2}, {"width": 2, "height": 1, "x": 3, "y": 2}, {"width": 1, "height": 2, "x": 6, "y": 2}, {"width": 2, "height": 1, "x": 3, "y": 3}, {"width": 4, "height": 2, "x": 0, "y": 4}, {"width": 1, "height": 2, "x": 4, "y": 4}, {"width": 1, "height": 2, "x": 6, "y": 4}, {"width": 4, "height": 2, "x": 0, "y": 6}, {"width": 1, "height": 2, "x": 4, "y": 6}, {"width": 1, "height": 2, "x": 6, "y": 6}]}
]
