---
title: "Compabs"
author: "Cameron Holdaway"
date: "7/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)
library(lme4)
<<<<<<< HEAD
=======
library(arm)
library(xtable)
>>>>>>> 6559fc76df0cac1a2a4d29f9819773f2e52c5bcf
library(lmerTest)
```
#### Start by reading in the data (CSV compiled in compabs_analysis.ipynb)
```{r}
df_block = read.csv('df_block.csv')
df_chat = read.csv('df_chat.csv')
df_trial = read.csv('df_trial.csv')

df_exit = read.csv('df_exit.csv')

df_chat$trialNum = as.numeric(as.character(df_chat$trialNum))
df_chat$repNum = as.numeric(as.character(df_chat$repNum))

df_trial <- transform(df_trial, trialScore = ifelse(is.na(trialScore), score, trialScore)) #fix score variable name change from livetest0 to pilots
#Group stimuli into scenes
df_trial = df_trial %>%
    dplyr::mutate(towerSet = case_when((leftTarget == 'L' | rightTarget == 'L')
                              & (leftTarget == 'Pi' | rightTarget == 'Pi')~ 'L/Pi',
                                (leftTarget == 'L' | rightTarget == 'L')
                            & (leftTarget == 'C' | rightTarget == 'C') ~ 'L/C', TRUE~'C/Pi'))
df_trial$trialNum = as.numeric(as.character(df_trial$trialNum))
df_trial$repNum = as.numeric(as.character(df_trial$repNum))
```

#### Find GameIDs that satisfy exclusion criteria
```{r}
 
#Preprocessing ensures all dyads in these CSVs have completed all trials

#How many dyads fulfill 75% Accuracy on 75% of trials
games75 = df_trial %>% 
  group_by(gameid, trialNum) %>% 
  filter(trialScore > 75  & repNum != 'practice') %>%
  group_by(gameid)%>% 
  tally %>% 
  filter(n/12 >=0.75) %>% 
  distinct(gameid)

#How many dyads said they were confused <-- this is probably inverse coded...
gamesConfused = df_exit %>% 
  filter(confused == 'yes') %>% 
  distinct(gameid)

#How many dyads said they spoke English
gamesEnglish = df_exit %>% 
  filter(nativeEnglish == 'yes') %>% 
  distinct(gameid)

gamesToKeep = intersect(games75, gamesConfused, gamesEnglish)
gamesToKeep
```

#### Plot first order analyses (word-block-message-score/repNum)
##### Word count/char count per repNum and trialNum
```{r}
df_chat$wordCount = sapply(strsplit(tolower(df_chat$content), " "), length)
df_chat$charCount =  nchar(tolower(df_chat$content))
df_chat$repNum = as.numeric(as.character(df_chat$repNum))
df_chat$trialNum = as.numeric(as.character(df_chat$trialNum))

df_chat %>% 
  dplyr::select(gameid,repNum, wordCount) %>% 
  group_by(gameid,repNum) %>% 
  summarise(wordCount = sum(wordCount)) %>% 
  group_by(repNum) %>% summarise(wordCountAvg = mean(wordCount)) %>% 
  ggplot(aes(x = repNum, y = wordCountAvg)) + geom_line()

df_chat %>% 
  dplyr::select(gameid,repNum,charCount) %>% 
  group_by(gameid,repNum) %>% 
  summarise(charCount = sum(charCount)) %>% 
  group_by(repNum) %>% summarise(charCountAvg = mean(charCount)) %>% 
  ggplot(aes(x = repNum, y = charCountAvg)) + geom_line()
```

##### Blocks placed, Score, etc.
```{r}
#Blocks placed per rep

#Average score per rep

```
### Join dfs to get score correlations
##### Score and Word Count
```{r}
#join chat and score to get correlation of words and score
a = df_chat %>% 
  dplyr::select(gameid,trialNum,repNum,wordCount) %>% 
  group_by(gameid,trialNum, repNum) %>% 
  summarise(wordCount = sum(wordCount))

b = df_trial %>% dplyr::select(gameid,trialNum, repNum,trialScore, towerSet) %>% 
  group_by(gameid,trialNum, repNum, towerSet) %>% 
  summarise(trialScore = max(trialScore)) #to deal with multiple practices

c = merge(a, b, by = c("gameid", "trialNum", "repNum"))
#d = merge(c,gamesToKeep, by = "gameid", all.y = TRUE)
c  %>% 
  ggplot(aes(x = trialNum, y = wordCount, color = repNum))+
  geom_point()+
  geom_smooth()

```


```{r}
View(c)
lin = lm(data = c, trialScore ~ trialNum + wordCount + repNum)
summary(lin)
#Score
lme = lmer(data = c, trialScore ~ repNum + (1 | gameid) + (1| towerSet))
summary(lme)   
#Word Count
lme = lmer(data = c, wordCount ~ repNum + (1 | gameid) + (1| towerSet))
summary(lme)  
#lme_null = lme4::lmer(data = c, p ~ 1 + (1|trialNum) + (1|wordCount))
#anova(lme,lme_null, test = "Chisq")
#lme4::ranef(lme)
#arm::se.ranef(lme)
broom.mixed::tidy(lme, effects = c('fixed', 'ran_vals'))
lme.table = broom.mixed::tidy(lme, effects = c('fixed', 'ran_vals'))
#xtable(lme.table)
```