---
title: "Compabs"
author: "Cameron Holdaway, Will McCarthy"
date: "09/21/2020"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)
library(lme4)
# library(arm)
# library(xtable)
library(lmerTest)
library(tidyboot)
theme_set(theme_classic())
theme_update(# axis labels
  axis.title = element_text(size = 28),
  # tick labels
  axis.text = element_text(size = 24),
  # title 
  title = element_text(size = 24),
  legend.position = 'FALSE', 
  text = element_text(size=16), 
  element_line(size=1), 
  element_rect(size=2, color="#00000"))
```

#### Read data, as output by compabs_analysis_df_generator.ipynb
```{r}
# import dataframes
df_block = read.csv('../results/csv/df_block.csv')
df_chat = read.csv('../results/csv/df_chat.csv')
df_trial = read.csv('../results/csv/df_trial.csv')
df_exit = read.csv('../results/csv/df_exit.csv')

df_block$repNum = as.numeric(as.character(df_block$repNum))
df_chat$trialNum = as.numeric(as.character(df_chat$trialNum))
df_chat$repNum = as.numeric(as.character(df_chat$repNum))

#Group stimuli into scenes
df_trial = df_trial %>%
    dplyr::mutate(towerSet = case_when((leftTarget == 'L' | rightTarget == 'L')
                              & (leftTarget == 'Pi' | rightTarget == 'Pi')~ 'L/Pi',
                                (leftTarget == 'L' | rightTarget == 'L')
                            & (leftTarget == 'C' | rightTarget == 'C') ~ 'L/C', TRUE~'C/Pi'))
df_block = df_block %>%
    dplyr::mutate(towerSet = case_when((leftTarget == 'L' | rightTarget == 'L')
                              & (leftTarget == 'Pi' | rightTarget == 'Pi')~ 'L/Pi',
                                (leftTarget == 'L' | rightTarget == 'L')
                            & (leftTarget == 'C' | rightTarget == 'C') ~ 'L/C', TRUE~'C/Pi'))
df_trial$trialNum = as.numeric(as.character(df_trial$trialNum))
df_trial$repNum = as.numeric(as.character(df_trial$repNum))

```

#### Filter trials that don't reach criterion
```{r}
#How many dyads fulfill 75% Accuracy on 75% of trials
games75 = df_trial %>% 
  group_by(gameid, trialNum) %>% 
  filter(trialScore > 75  & repNum != 'practice') %>%
  group_by(gameid)%>% 
  tally %>% 
  filter(n/12 >=0.75) %>% 
  distinct(gameid)

#How many dyads said they were confused <-- this is probably inverse coded...
gamesConfused = df_exit %>% 
  filter(confused == 'yes') %>% 
  distinct(gameid)

#How many dyads said they spoke English
gamesEnglish = df_exit %>% 
  filter(nativeEnglish == 'yes') %>% 
  distinct(gameid)

gamesToKeep = intersect(games75, gamesConfused, gamesEnglish)
```

#### Filter trials that don't reach criterion
```{r}

```
## Performance
```{r}
trials <- df_trial %>% 
  filter(practice=='False')
```

### Accuracy 

#### Accuracy across reps

```{r}
acc.boot <- trials %>%
  group_by(repNum) %>%
  tidyboot_mean(column=trialScore, nboot=1000)
acc.boot
```


```{r}
acc.boot %>%
  ggplot(aes(x=repNum,y=empirical_stat, color = "#99373e")) +
    geom_errorbar(aes(ymin=ci_lower, ymax = ci_upper), width = 0, size = 1.5,
                  data = acc.boot) +  
    geom_line(size=1.5)+
    geom_point(size = 4) +
    ylab("Accuracy (F1)") +
    xlab("Repetition") +
    theme_few() +
    # scale_x_continuous(breaks = round(seq(1, 4, by =1),1)) +
    # xlim(c(0.5,4.5)) +  
    # ylim(c(0.6,1)) +
    #scale_x_continuous(limits = c(0.6,4.4), breaks = c(1,2,3,4),labels=c('first', '2nd','3rd','final')) +
    # scale_y_continuous(breaks = seq(-0.5,2.5,0.5)) +
    theme(legend.position = 'FALSE', text = element_text(size=16), element_line(size=1), element_rect(size=2, color="#00000"))

```

```{r}
m.acc = lmer(data = trials, trialScore  ~ repNum + (1 | gameid) + (1 | towerSet))
summary(m.acc)

```

### Word Count 

#### Word count across trials
```{r}
wc.boot <- trials %>%
  group_by(repNum) %>%
  tidyboot_mean(column=word_count, nboot=100)
wc.boot
```


```{r}
wc.boot %>%
  ggplot(aes(x=repNum,y=empirical_stat, color = "#99373e")) +
    geom_errorbar(aes(ymin=ci_lower, ymax = ci_upper), width = 0, size = 1.5,
                  data = wc.boot) +  
    geom_line(size=1.5)+
    geom_point(size = 4) +
    ylab("word count") +
    xlab("repetition") +
    theme_few() +
    # scale_x_continuous(breaks = round(seq(1, 4, by =1),1)) +
    # xlim(c(0.5,4.5)) +  
    # ylim(c(0.6,1)) +
    #scale_x_continuous(limits = c(0.6,4.4), breaks = c(1,2,3,4),labels=c('first', '2nd','3rd','final')) +
    # scale_y_continuous(breaks = seq(-0.5,2.5,0.5)) +
    theme(legend.position = 'FALSE', text = element_text(size=16), element_line(size=1), element_rect(size=2, color="#00000"))

```

### Character Count 

#### Character count across trials
```{r}
cc.boot <- trials %>%
  group_by(repNum) %>%
  tidyboot_mean(column=char_count, nboot=100)
cc.boot
```


```{r}
cc.boot %>%
  ggplot(aes(x=repNum,y=empirical_stat, color = "#99373e")) +
    geom_errorbar(aes(ymin=ci_lower, ymax = ci_upper), width = 0, size = 1.5,
                  data = cc.boot) +  
    geom_line(size=1.5)+
    geom_point(size = 4) +
    ylab("character count") +
    xlab("repetition") +
    theme_few() +
    # scale_x_continuous(breaks = round(seq(1, 4, by =1),1)) +
    # xlim(c(0.5,4.5)) +  
    # ylim(c(0.6,1)) +
    #scale_x_continuous(limits = c(0.6,4.4), breaks = c(1,2,3,4),labels=c('first', '2nd','3rd','final')) +
    # scale_y_continuous(breaks = seq(-0.5,2.5,0.5)) +
    theme(legend.position = 'FALSE', text = element_text(size=16), element_line(size=1), element_rect(size=2, color="#00000"))

```

### Num messages 

#### Number of messages across trials
```{r}
cc.boot <- trials %>%
  group_by(repNum) %>%
  tidyboot_mean(column=n_messages, nboot=100)
cc.boot
```

```{r}
cc.boot %>%
  ggplot(aes(x=repNum,y=empirical_stat, color = "#99373e")) +
    geom_errorbar(aes(ymin=ci_lower, ymax = ci_upper), width = 0, size = 1.5,
                  data = cc.boot) +  
    geom_line(size=1.5)+
    geom_point(size = 4) +
    ylab("messages") +
    xlab("repetition") +
    theme_few() +
    # scale_x_continuous(breaks = round(seq(1, 4, by =1),1)) +
    # xlim(c(0.5,4.5)) +  
     ylim(c(0,5)) +
    #scale_x_continuous(limits = c(0.6,4.4), breaks = c(1,2,3,4),labels=c('first', '2nd','3rd','final')) +
    # scale_y_continuous(breaks = seq(-0.5,2.5,0.5)) +
    theme(legend.position = 'FALSE', text = element_text(size=16), element_line(size=1), element_rect(size=2, color="#00000"))

```




```{r}

```
