---
title: "Referring_expressions_dist"
author: "Cameron Holdaway"
date: "1/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
theme_set(theme_classic())
theme_update(# axis labels
  axis.title = element_text(size = 28),
  # tick labels
  axis.text = element_text(size = 24),
  # title 
  title = element_text(size = 24),
  legend.position = 'FALSE', 
  text = element_text(size=16), 
  element_line(size=1), 
  element_rect(size=2, color="#00000"))

primary_color = '#21606C'
secondary_color = '#22AAAA'
```

## R Markdown

To analyze the distribution of referring expressions as counted by Justin and Julia.
We will sum the number of expressions referring to towers and blocks in for each dyad in each rep, then take the average. Then plot the change in distribution over reps

## Read in Data
```{r}
dat = read_csv('ORLR-Justin-Julia-rating.csv')

#Sum ref exp then divide by two (since we have two raters)
dat_grouped = dat %>%  group_by(dyad, trialNum,repNum,refType) %>% 
  summarise(sum_ref = sum(refExp)/2)
dat_grouped
dat_grouped = spread(dat_grouped,refType,sum_ref)
dat_grouped$mixType = ifelse(dat_grouped$block>0 & dat_grouped$tower > 0, 'mixed', ifelse(dat_grouped$block>0, 'block',ifelse(dat_grouped$tower>0,'tower','none')))




# #Take mean by repNum and refType
# df = dat_grouped %>% group_by(repNum, refType) %>% 
#   summarise(mean_ref = mean(sum_ref, na.rm = TRUE))
# df

```

### Plot
```{r}

df_ref =  as.data.frame(table(dat_grouped$repNum, dat_grouped$mixType))
df_ref = df_ref %>% rename(repNum = Var1, mixType = Var2)
df_ref = df_ref %>% filter(mixType != 'none')
ggplot(df_ref, aes(x=repNum, y = Freq, fill=mixType)) + 
    geom_bar(stat="identity",position = 'fill')+
    scale_fill_manual(values=c('black', primary_color, "light grey"))+
  xlab("repetition")+
  ylab('frequency')
ggsave("referring_expressions_barplot.pdf")
```
